version: '3.8'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
